/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllPanels_custom;



/**
 *
 * @author shayan
 */
public class Tv_1to20 extends javax.swing.JPanel  {

    int id;
    int gameindex;
    namaMain nammain;
    boolean selected;
    boolean newsha = false;

    /**
     * Creates new form Tv_1to20
     */
    public Tv_1to20() {
        newsha = false;
        initComponents();
        newsha = true;
    }

    public Tv_1to20(int id, namaMain nammain) {
        newsha = false;
        initComponents();
        this.id = id;
        this.nammain = nammain;
        jToggleButtonIndex.setText(String.valueOf(10*(id + 1)));
        jComboBox1.removeAllItems();
        for (int i = 0; i < nammain.database0.getGames().size()-3; i++) {
            jComboBox1.addItem(nammain.database0.getGame(i).getGamename());

        }
        jComboBox1.setSelectedIndex(nammain.database0.getSelectedGames(id));
        gameindex= jComboBox1.getSelectedIndex();
        newsha = true;
    }

//    public Tv_1to20(int id, namaMain nammain, String code) {
//        newsha = false;
//        initComponents();
//
//        this.id = id;
//        jToggleButtonIndex.setText(String.valueOf((id + 1) * 10));
//        this.nammain = nammain;
//
//        newsha = true;
//    }

    public int getId() {
        return id;
    }

//    public void setIndex(int id) {
//        this.id = id;
//    }
    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        boolean b = newsha;
        newsha=false;
        this.selected = selected;
        jToggleButtonIndex.setSelected(selected);
         newsha=b;
    }

    public int getGameindex() {
        return gameindex;
    }

    public void setGameindex(int gameindex) {
//        boolean b = newsha;
//        newsha = false;
        jComboBox1.setSelectedIndex(gameindex);
//        newsha = true;
        this.gameindex = gameindex;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jToggleButtonIndex = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jToggleButtonIndex.setText("1");
        jToggleButtonIndex.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonIndexActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButtonIndex);

        add(jPanel2);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonIndexActionPerformed
        // TODO add your handling code here:
if(newsha && jToggleButtonIndex.isSelected()  )
       if(! nammain.tv20Active(id, jComboBox1.getSelectedIndex()))jToggleButtonIndex.setSelected(false);
//        System.out.println("980423- id="+id+"   jComboBox1.getSelectedIndex()="+ jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jToggleButtonIndexActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (newsha) {
         gameindex = jComboBox1.getSelectedIndex();
        nammain.database0.setSelectedGames(id, gameindex);
        nammain.controll.saveDatabase0();
//         nammain.controolPack.addDatapackImage(11+id, nammain.datgabaseFileAdd.getgameicon9807(gameindex,id));
          nammain.controll.SendControolPack();
                          }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButtonIndex;
    // End of variables declaration//GEN-END:variables

    void setSelected() {
        gameindex = jComboBox1.getSelectedIndex();
//          nammain.controolPack.addDatapackImage(11+id, nammain.datgabaseFileAdd.getgameicon9807(gameindex,id));
    }

    void clear() {
        jToggleButtonIndex.setSelected(false);
    }

   

}
