/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package runner;

import ControllPanels.Controll;
import JSO.Com.Communicate.Server;
import JSO.Com.Main.Settings;

import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author shayan
 */
public class MainAPPFull extends javax.swing.JFrame {

//    Client outold[];
    private final Server server;
    Controll controll;
    Settings settings;
//    Displayer displayer;

    /**
     * Creates new form Letter2
     */
    public MainAPPFull() {
        int i = 0;
try {
           Image im = ImageIO.read(new File("pictures\\shayanMaded.png")); 
            this.setIconImage(im);
ImageIcon iChing = new ImageIcon("pictures\\shayanMaded.png"); 
//btnReport.setIcon(iChing);
        } catch (IOException ex) {
//            Logger.getLogger(Display_Frame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Imagepanel did not load Image:");
        }
        try {
//             Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(
                    UIManager.getCrossPlatformLookAndFeelClassName());

        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }
//          setDefaultLookAndFeelDecorated(true);

//        displayer = new Displayer(true);
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//        try {
//            Runtime.getRuntime().exec("OpenGLOutput.exe");
//        } catch (IOException ex) {
//            Logger.getLogger(MainAPPFull.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
         server = new Server();
        new Thread(server).start();
        settings = new Settings(server);

//        server.setDisplay_Frame(displayer.getDisplay_Frame());
//        server.setWritesocket1_0_SendDirectly(true);
//        new Thread(server).start();
 //       settings = new Settings(server);
        controll = new Controll(server);

                jTabbedPane1.add(" play ", controll);
        jTabbedPane1.add("Settings ", settings);

      //   jTabbedPane1.setSelectedIndex(1);
server.setServerFREEe(true);
        settings.sendSetting();
        
        
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         this.addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
//                    int i=JOptionPane.showConfirmDialog(null, "Are you sure?","Exit",0);
//                    if(i==0)
                    {
                         settings.sendexit();
                        System.exit(0);//cierra aplicacion
                }}
            });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAPPFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAPPFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAPPFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAPPFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAPPFull().setVisible(true);

            }

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
